作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [75]:
import numpy as np

In [76]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [77]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
subject = ['english_score', 'math_score', 'chinese_score']
subject_score = [english_score, math_score, chinese_score]

def score_calculate(subject, subject_score):
    j = 0
    for i in subject_score:
        print(subject[j])
        j+=1
        print("成績平均為：", np.nanmean(i))
        print("成績最大值為：", np.nanmax(i))
        print("成績最小值為：", np.nanmin(i))
        print("成績標準差為：", np.nanstd(i), '\n')

score_calculate(subject, subject_score)

english_score
成績平均為： 67.16666666666667
成績最大值為： 89
成績最小值為： 48
成績標準差為： 13.433995020924426 

math_score
成績平均為： 66.6
成績最大值為： 85.0
成績最小值為： 60.0
成績標準差為： 9.707728879609279 

chinese_score
成績平均為： 75.33333333333333
成績最大值為： 90
成績最小值為： 65
成績標準差為： 8.825468196582484 



In [78]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score = np.array([60,85,60,68,np.nan,60])
math_score[4] = 55
print('math_score')
print("成績平均為：", np.nanmean(math_score))
print("成績最大值為：", np.nanmax(math_score))
print("成績最小值為：", np.nanmin(math_score))
print("成績標準差為：", np.nanstd(math_score))

math_score
成績平均為： 64.66666666666667
成績最大值為： 85.0
成績最小值為： 55.0
成績標準差為： 9.860132971832694


In [81]:
subject_score = [english_score, math_score, chinese_score]
subject_score

[array([55, 89, 76, 65, 48, 70]),
 array([60., 85., 60., 68., 55., 60.]),
 array([65, 90, 82, 72, 66, 77])]

In [82]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

np.corrcoef(subject_score)

# 答案是英文，看最左下，97.79%

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])